services:
  - type: web
    name: angel-transportation
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_WEBHOOK_SECRET
        sync: false
      - key: TERMII_API_KEY
        sync: false
